"use client";
import "./globals.css";
import { Darker_Grotesque } from "next/font/google";
import Script from "next/script";
import Head from "next/head";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import React, { useEffect } from "react";

/* export const metadata = {
  title: "Beolika Themes",
  description: "Generated by create next app",
}; */

const darker = Darker_Grotesque({ weight: ["400", "500", "600", "700", "800", "900"], subsets: ["latin"], variable: "--font-darker" });
const sego = localFont({
  src: [
    {
      path: "../../public/fonts/sego.ttf",
    },
  ],
  variable: "--font-sego",
});

const glacialRegular = localFont({
  src: [
    {
      path: "../../public/fonts/glacialRegular.otf",
    },
  ],
  variable: "--font-glacial-regular",
});

const glacialBold = localFont({
  src: [
    {
      path: "../../public/fonts/glacialBold.otf",
    },
  ],
  variable: "--font-glacial-bold",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  useEffect(() => {
    document.addEventListener("snipcart.ready", (e) => {
      const snipcartReadyEvent = e as CustomEvent;
      const Snipcart = snipcartReadyEvent.detail.sdk;

      Snipcart.api.theme.customization.registerPaymentFormCustomization({
        input: {
          color: "white"
        },
        label: {
          color: "white"
        }
      });
    });
  }, []);

  return (
    <html lang="en" className={`${darker.variable} ${sego.variable} ${glacialRegular.variable} ${glacialBold.variable}`}>
      <Head>
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
      </Head>
      <body className="min-w-screen bg-[var(--color-primary)]" suppressHydrationWarning={true}>
        {children}
        <Toaster position="bottom-center" reverseOrder={false} />
        <Script
          async
          src="https://cdn.snipcart.com/themes/v3.4.1/default/snipcart.js"
          id="snipcart"
          data-api-key="YzhhNzM3YmMtNDY4Ny00OGYxLTg3ZDYtNzIxMDI5ZmQwYmE5NjM4MTQ1MTk2OTM4NDY2NzEy"
          data-config-modal-style="side"></Script>
      </body>
    </html>
  );
}
